name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  serverless:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/nestjs-serverless-CI.yml@master
    with:
      node_version: '18.x'
      mysql_version: mysql:5.7
      mysql_db_name: boilerplate-nestjs-serverless-test