name: DEPLOY - DEV
on:
  workflow_dispatch:
  push:
   branches:
    - master
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          php-version: "8.1"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install Node Dependencies
        run: npm ci
      - name: Deploy
        run: npx serverless deploy
