name: DESTROY - DEV
on:
   workflow_dispatch:
jobs:
  serverless:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/nestjs-serverless-destroy.yml@master
    with:
      node_version: '18.x'
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
     